name: "Setup"
description: "Setup"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4
    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version-file: ".node-version"
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
